import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Play, Pause, SkipForward, SkipBack, Volume2, Music } from 'lucide-react';
import { TRACKS } from '../constants';

export const MusicPlayer: React.FC = () => {
  const [currentTrackIndex, setCurrentTrackIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [volume, setVolume] = useState(0.5);
  const audioRef = useRef<HTMLAudioElement>(null);

  const currentTrack = TRACKS[currentTrackIndex];

  useEffect(() => {
    if (audioRef.current) {
      audioRef.current.volume = volume;
    }
  }, [volume]);

  useEffect(() => {
    if (isPlaying) {
      audioRef.current?.play().catch(() => setIsPlaying(false));
    } else {
      audioRef.current?.pause();
    }
  }, [isPlaying, currentTrackIndex]);

  const togglePlay = () => setIsPlaying(!isPlaying);

  const handleNext = () => {
    setCurrentTrackIndex((prev) => (prev + 1) % TRACKS.length);
  };

  const handlePrev = () => {
    setCurrentTrackIndex((prev) => (prev - 1 + TRACKS.length) % TRACKS.length);
  };

  return (
    <div className="w-full max-w-md bg-slate-950/80 backdrop-blur-xl border border-white/5 rounded-2xl p-4 flex items-center gap-4 shadow-2xl relative overflow-hidden" id="music-player">
      {/* Background Glow */}
      <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-cyan-500 to-transparent opacity-50"></div>
      
      {/* Track Art */}
      <div className="relative w-16 h-16 shrink-0 rounded-lg overflow-hidden border border-white/10" id="track-art-container">
        <AnimatePresence mode="wait">
          <motion.img
            key={currentTrack.id}
            initial={{ opacity: 0, scale: 1.2 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.8 }}
            src={currentTrack.coverUrl}
            alt={currentTrack.title}
            className="w-full h-full object-cover"
          />
        </AnimatePresence>
        {isPlaying && (
          <div className="absolute inset-0 bg-black/40 flex items-center justify-center">
             <div className="flex gap-[2px] items-end h-4">
                {[...Array(4)].map((_, i) => (
                  <motion.div
                    key={i}
                    animate={{ height: [4, 16, 8, 12, 4] }}
                    transition={{ repeat: Infinity, duration: 0.8, delay: i * 0.1 }}
                    className="w-[2px] bg-cyan-400"
                  />
                ))}
             </div>
          </div>
        )}
      </div>

      {/* Track Info */}
      <div className="flex-1 min-w-0" id="track-info">
        <h3 className="text-white font-bold text-sm truncate tracking-tight">{currentTrack.title}</h3>
        <p className="text-white/40 text-xs truncate">AI GENERATED BY {currentTrack.artist}</p>
      </div>

      {/* Controls */}
      <div className="flex items-center gap-2" id="player-controls">
        <button onClick={handlePrev} className="p-2 text-white/60 hover:text-white transition-colors" id="prev-btn">
          <SkipBack size={18} />
        </button>
        
        <button
          onClick={togglePlay}
          className="w-10 h-10 flex items-center justify-center bg-white text-black rounded-full hover:scale-105 transition-transform"
          id="play-pause-btn"
        >
          {isPlaying ? <Pause size={20} fill="currentColor" /> : <Play size={20} fill="currentColor" className="ml-1" />}
        </button>

        <button onClick={handleNext} className="p-2 text-white/60 hover:text-white transition-colors" id="next-btn">
          <SkipForward size={18} />
        </button>
      </div>

      {/* Volume Slider */}
      <div className="hidden sm:flex items-center gap-2 ml-2 pr-2" id="volume-control">
         <Volume2 size={14} className="text-white/40" />
         <input
          type="range"
          min="0"
          max="1"
          step="0.01"
          value={volume}
          onChange={(e) => setVolume(parseFloat(e.target.value))}
          className="w-16 h-1 bg-white/10 rounded-full appearance-none cursor-pointer accent-cyan-400"
         />
      </div>

      <audio
        ref={audioRef}
        src={currentTrack.url}
        onEnded={handleNext}
        onPlay={() => setIsPlaying(true)}
        onPause={() => setIsPlaying(false)}
      />
    </div>
  );
};
